### ISSUE TITLE
Release v0.9

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#740]
We should perform a merge of IBPSA Lib into AixLib soon.  
IBPSA now also have its first conversion script located [here](https://github.com/ibpsa/modelica-ibpsa/tree/master/IBPSA/Resources/Scripts/Dymola).

- [x] Take care that IBPSA's CS is fired also in AixLib and of course that the file is copied to AixLib repo.
- [x] Merge IBPSA into AixLib.
- [x] Add license changes manual #717 
- [x] Move packages to `Obsolete` folder acc. to #746 
- [x] Revise [the wiki section](https://github.com/RWTH-EBC/AixLib/wiki/AixLib-and-Modelica-IBPSA-Library-(former-Annex-60)) where necessary and the paragraph below.
- [x] Resolve issues with CI #781 
- [x] Integrate #724 for clearer heatpump and chiller seperation 
- [x] Try to solve errors (see this [comment](https://github.com/RWTH-EBC/AixLib/pull/774#issuecomment-551215184)) in AixLib bevore merging `dev` into `master` and propose changes to `IBPSA`.

**Comment by cvering** [comment]
Hey you all! It is a great idea to do the merge. Please wait for IBPSA's issue https://github.com/ibpsa/modelica-ibpsa/issues/1093 that we have a clear structure of our refrigerants from issue #408 and no problems with naming.

**Comment by DaJansenGit** [comment]
Since @cvering agreed, we can do the merge now.

**Comment by PMehrfeld** [comment]
We still need to address the task in the first comment.
@DaJansenGit : Would you please have a look at branch `781_CITests` and #781. Probably we can just delete the branch and close the issue. 

Before merging `dev` (incl. latest IBPSA) into `master` and release a version, I would like to wait another week to eventually detect bugs.

**Comment by PMehrfeld** [comment]
@DaJansenGit: I am a bit confused that [this commit](https://github.com/ibpsa/modelica-ibpsa/commit/6732058d35c9786d8579cceec74010cb59bff978#diff-353aa2db5b79ad891dd22adabc538f80) in the IBPSA lib from 3 June is not in our `dev`.  
Since you told me to do a new merge from `IBPSA master` into `AixLib dev` you can: 

- [ ] check if this change was applied. 

It might be an issue with as it affects the UsersGuide, which is HTML code in the `package.mo` of the `Fluid` subpackge.

**Comment by DaJansenGit** [comment]
after the merge of #770 we will now 
- [ ] merge the ibpsa egain

**Comment by DaJansenGit** [comment]
> @DaJansenGit: I am a bit confused that [this commit](https://github.com/ibpsa/modelica-ibpsa/commit/6732058d35c9786d8579cceec74010cb59bff978#diff-353aa2db5b79ad891dd22adabc538f80) in the IBPSA lib from 3 June is not in our `dev`.
> Since you told me to do a new merge from `IBPSA master` into `AixLib dev` you can:
> 
> * [ ]  check if this change was applied.
> 
> It might be an issue with as it affects the UsersGuide, which is HTML code in the `package.mo` of the `Fluid` subpackge.

For any reason this change is not applied by the merge script. We did it manual with dde4aac16ce3f6d046de0333f96524f13b53db27

**Comment by DaJansenGit** [comment]
the release is done. You can find it here https://github.com/RWTH-EBC/AixLib/releases/tag/v0.9.0
