### ISSUE TITLE
makeFastHvacGreatAgain

### ISSUE THREAD

**Issue by Dawac** [RWTH-EBC/AixLib#790]
In addition to #309:
We would like to implement some features to the FastHVAC to hopefully make it a little bit more consistent and stable.

One of the goals is to 

Tasks:
- [x] mflow shall be defined as flow variable again
- [x] new model for a generic splitter with variable split ratio between the ports
- [ ] implementation of a leakage massflow depending on a nominal flow for all components
- [ ] new demand model with conservation equation
- [X] restructure the package order (see also #564)

**Comment by DaJansenGit** [comment]
The massflow is implemented as a flow variable again. This was possible by adding a dummy potential variable. Changes made:

### Rework enthalpy port:
- create dummy potential variable  (hidden in results to prevent confusion)
- remove not needed temperature and specific heat capacity variables 
- make enthalpy a stream variable and call it h_outflow

### General changes:
- h_outflow at port a is always zero (no backflow in FastHVAC)
- h_outflow at port b described with inStream()
- rework splitter model 

### Todo: Models/packages to check and change:
- [ ] DHWHeatExchanger
- [ ] Radiators 
- [ ] Fluid Source
- [ ] Pump
- [ ] HeatPump
- [ ] CHP
- [ ] Boiler
- [ ] Pipemodels
- [ ] Sensors
- [ ] Storages
- [ ] Sinks
- [ ] Valves

### Todo: After merging into development and integration of #740 
- [ ] move manifold to obsolete (not needed anymore due to flow variable does this by itself)

**Comment by DaJansenGit** [comment]
we have a problem with the component `AixLib.FastHVAC.HeatGenerators.BaseClasses.EvaporatorCondenserWithCapacity`
For any reason the two missing equations for `GOut` and `GInn` throw an error when checking in the FastHVAC model but not in it's counterpart model `AixLib.Fluid.HeatExchangers.EvaporatorCondenserWithCapacity`.
If we set a default value for the variables  `GOut` and `GInn` the model checks, but this seems quite dangerous to me.
Further investigation needed...
